config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources "challenges" do
  	collection do
  		get "dashboard"
  	end
  end

  root 'challenges#index'
  post '/short_url' , to: "challenges#short_url"
  get '/:search', to: "challenges#my_link" # dynamic url route

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
	scope :get_bit_code_url, ->(bit_code) { find_by_bit_code(bit_code).url } # wrote scope to find url

	def self.get_bit_code
		bit_code = (0..10).map { ('a'..'z').to_a[rand(50)] }.join

		# creating bit code till bit code is not present database

		until !Challenge.bit_code_present(bit_code)  do
			bit_code = (0..10).map { ('a'..'z').to_a[rand(50)] }.join
		end

		return bit_code	
	end

	# checking bit_code present in database or not
	def self.bit_code_present(bit_code) 
		if(Challenge.get_bit_code_url(bit_code) rescue false)
			return true
		else
			return false
		end		
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

	# home page 

	def index
	end

	# dashboard is showing all shorten url list as per frequenty used url order

	def dashboard
		@challenges = Challenge.all.order("count desc").limit(100)
	end	

	# creating shorten url 

	def short_url
		url = params[:search].gsub("http://" , "").gsub("https://" , "")
		@challenge = Challenge.find_by_url( url)
		if @challenge.present? # checking url already present in database or not ?
			@challenge.count =  @challenge.count + 1 # adding url hit count
		else
		  bit_code = Challenge.get_bit_code  # creating bit code
			@challenge = Challenge.new(:url=>  url, :count => 1 , :bit_code => bit_code)
		end
		@challenge.save # saving record
	end

	# redirecting url 

	def my_link 
		redirect_to "http://#{Challenge.get_bit_code_url(params[:search])}" # getting url by using bit code
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_search.html.haml
%p Your url is :
%p= link_to @challenge.url , "http://#{@challenge.url}"  , :target => :blank
%p Your shorten url is :
%p= link_to "#{root_url}#{@challenge.bit_code}" , "#{root_url}#{@challenge.bit_code}"  , :target => :blank

app/views/challenges/dashboard.html.haml
%table{:class => "table table-hover"}
  %tr
    %th URL List :
  - @challenges.each_with_index do |challenge, i|
    %tr
      %td
        = "#{i + 1})"
        = link_to "#{root_url}#{challenge.bit_code}" , "#{root_url}#{challenge.bit_code}"  , :target => :blank

app/views/challenges/index.html.haml
%br
%div
  = link_to "Dashboard" , dashboard_challenges_path
%br
%br
%div   
  = form_tag("/short_url", method: "post" , :remote => true ) do
    = text_field_tag(:search, "" , {:placeholder=>"SHORTEN.."})
    = submit_tag("SHORTEN")

  %br
  %br 
  #shrturl

app/views/challenges/short_url.js.erb
$("#shrturl").html("<%=j render :partial => 'search' %>"); 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shorten URL
    = csrf_meta_tags
    = stylesheet_link_tag    'application' , 'bootstrap.min'
    = javascript_include_tag 'application'
  %body.main
    = yield